services:
  - type: web
    name: fb-medical-chatbot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FB_PAGE_ACCESS_TOKEN
        sync: false
      - key: FB_VERIFY_TOKEN
        sync: false
      - key: FB_APP_SECRET
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GOOGLE_SERVICE_ACCOUNT_EMAIL
        sync: false
      - key: GOOGLE_PRIVATE_KEY
        sync: false
      - key: GOOGLE_SHEET_ID
        sync: false
